name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Install Qt5 using jurplel/install-qt-action
      - name: Install Qt5
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          arch: 'win64_msvc2019_64'

      # 3️⃣ Configure CMake with Qt path
      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_PREFIX_PATH="${{ env.QTDIR }}/5.15.2/msvc2019_64/lib/cmake"

      # 4️⃣ Build project
      - name: Build project
        run: cmake --build build --config Release

      # 5️⃣ Upload EXE
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: YIVApp-EXE
          path: build/Release/YIVApp.exe
