name: Build Qt C++ App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.6.2'
          host: 'windows'
          target: 'desktop'

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Configure CMake
        run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config Release

      - name: Copy .exe to artifact
        run: |
          mkdir output
          copy build\Release\your_app.exe output\

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: qt-exe
          path: output/
